# Generated by Django 3.1.1 on 2020-09-20 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_message',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='send_message',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
