# Generated by Django 3.1.1 on 2020-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0002_auto_20200920_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('post_at', models.DateTimeField()),
                ('is_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
