# Generated by Django 3.1.1 on 2020-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0004_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('conversation_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
