# Generated by Django 3.1.1 on 2020-09-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0005_send_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send_Conversation',
        ),
    ]
